name: Firebase CI/CD

on:
  push:
    branches: [main]  # or change to 'dev' if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Change to your Flutter version

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug --build-name=1.0.0 --build-number=1

#      - name: Build iOS (optional, requires macOS runner)
#        run: flutter build ios --debug --build-name=1.0.0 --build-number=1 --no-codesign

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload artifact to Firebase App Distribution
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{ secrets.FIREBASE_ID_FOR_DEV }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIAL_FILE_CONTENT }}
          groups: android
          file: build/app/outputs/flutter-apk/app-debug.apk
